#!/usr/bin/env python3
"""Hook de Anonimato -- auto-corrige evidências de IA no código.

Localmente: aplica correções automáticas nos arquivos.
Em CI: apenas reporta problemas (dry-run).

Regra: CLAUDE.md seção 2 -- anonimato absoluto em commits e código.
Exceções técnicas permitidas: api_key, provider, model, config,
ANTHROPIC_API_KEY, OPENAI_API_KEY, e similares.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

IS_CI = os.environ.get("CI", "").lower() == "true"

EXCLUSIONS = [
    "check_anonymity",
    "hooks/",
    "scripts/",
    ".github/workflows",
    ".gitignore",
    ".env.example",
    "CLAUDE.md",
    "GSD.md",
    "docs/adr",
    "docs/sprints",
    "docs/AUTOMACAO_BANCARIA.md",
    "docs/ARMADILHAS.md",
    "pyproject.toml",
    "requirements.txt",
    ".pre-commit-config.yaml",
]

REPLACEMENTS: list[tuple[str, str]] = [
    ("As an AI language model", ""),
    ("as an AI language model", ""),
    ("Generated by Claude", "Gerado automaticamente"),
    ("Generated by GPT", "Gerado automaticamente"),
    ("Generated by AI", "Gerado automaticamente"),
    ("Suggested by Claude", ""),
    ("Suggested by AI", ""),
    ("Claude Code", "agente de código"),
    ("Claude CLI", "ferramenta CLI"),
    ("Claude Sonnet", "modelo externo"),
    ("Claude Opus", "modelo externo"),
    ("Claude Haiku", "modelo externo"),
    ("Anthropic", "provedor"),
]

FALSE_POSITIVE_RE = re.compile(
    r"Claude\s+(?:Shannon|Debussy|Monet|Levi-Strauss|Bernard|Rains)",
    re.IGNORECASE,
)

STANDALONE_CLAUDE_RE = re.compile(r"\bClaude\b")

COAUTHOR_RE = re.compile(
    r"Co-Authored-By:.*(?:Claude|anthropic|noreply@anthropic)",
    re.IGNORECASE,
)

COMMENT_AI_RE = re.compile(
    r"^[ \t]*#.*(claude|anthropic).*(sugeriu|escreveu|fez|criou|gerou|wrote|made|created)",
    re.IGNORECASE,
)

# Identificadores técnicos legítimos que NÃO devem ser alterados
TECH_EXCEPTIONS = re.compile(
    r"ANTHROPIC_API_KEY|OPENAI_API_KEY|api_key|provider=|\.anthropic\.com|anthropic-version|"
    r"import anthropic|from anthropic|anthropic\.(Anthropic|AsyncAnthropic|messages)",
    re.IGNORECASE,
)


def is_excluded(filepath: str) -> bool:
    """Retorna True se o arquivo está em caminho isento."""
    return any(exc in filepath for exc in EXCLUSIONS)


def fix_line(line: str, filepath: str) -> str | None:
    """Corrige uma linha. Retorna None para remover, string para manter."""
    if FALSE_POSITIVE_RE.search(line):
        return line

    if TECH_EXCEPTIONS.search(line):
        return line

    if COAUTHOR_RE.search(line):
        return None

    if filepath.endswith(".py") and COMMENT_AI_RE.search(line):
        return None

    result = line
    for old, new in REPLACEMENTS:
        if old in result:
            result = result.replace(old, new)

    if STANDALONE_CLAUDE_RE.search(result):
        result = STANDALONE_CLAUDE_RE.sub("agente", result)

    return result


def fix_file(filepath: str, dry_run: bool = False) -> tuple[int, list[str]]:
    """Auto-corrige violações de anonimato em um arquivo."""
    if is_excluded(filepath):
        return 0, []

    path = Path(filepath)
    if not path.exists():
        return 0, []

    try:
        content = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return 0, []

    lines = content.splitlines(keepends=True)
    new_lines: list[str] = []
    fixes: list[str] = []

    for i, line in enumerate(lines):
        fixed = fix_line(line, filepath)

        if fixed is None:
            fixes.append(f"  L{i + 1}: removida")
        elif fixed != line:
            fixes.append(f"  L{i + 1}: corrigido")
            new_lines.append(fixed)
        else:
            new_lines.append(line)

    new_content = "".join(new_lines)

    if new_content != content:
        if not dry_run:
            path.write_text(new_content, encoding="utf-8")
        return len(fixes), fixes

    return 0, []


def format_report(all_reports: dict[str, list[str]]) -> str:
    """Formata relatório final das correções aplicadas."""
    lines: list[str] = []
    lines.append("")
    lines.append("=" * 60)
    lines.append(
        "ANONIMATO: Auto-corrigido" if not IS_CI else "ANONIMATO: Problemas detectados (CI)"
    )
    lines.append("=" * 60)

    total = 0
    for filepath, descs in all_reports.items():
        lines.append(f"\n  {filepath}:")
        for d in descs:
            lines.append(f"    {d}")
        total += len(descs)

    lines.append("")
    if IS_CI:
        lines.append(f"Total: {total} problemas em {len(all_reports)} arquivos")
        lines.append("Rode pre-commit localmente para aplicar correções")
    else:
        lines.append(f"Total: {total} correções em {len(all_reports)} arquivos")
    lines.append("=" * 60)
    lines.append("")

    return "\n".join(lines)


def _get_staged_files() -> list[str]:
    """Retorna arquivos staged no git."""
    import subprocess

    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
            capture_output=True,
            text=True,
            check=False,
        )
        return [f for f in result.stdout.strip().split("\n") if f]
    except (subprocess.SubprocessError, FileNotFoundError):
        return []


def main() -> int:
    """Ponto de entrada principal."""
    files = sys.argv[1:] if len(sys.argv) > 1 else _get_staged_files()
    all_reports: dict[str, list[str]] = {}

    for f in files:
        num_fixes, descriptions = fix_file(f, dry_run=IS_CI)
        if num_fixes > 0:
            all_reports[f] = descriptions

    if all_reports:
        print(format_report(all_reports))
        if IS_CI:
            return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())

# "A linguagem é a casa do ser." -- Martin Heidegger
